### ISSUE TITLE
Collect outstanding $210 from unpaid pre-registrants

### ISSUE THREAD

**Issue by twwilliams** [GFGR/sandbox#5]

**Comment by 6Firewall6** [comment]
Emails have been sent to the people to remind them.

**Comment by 6Firewall6** [comment]
currently at 185 outstanding

**Comment by 6Firewall6** [comment]
Registration closed with only one of the missing payments being made. Non payments removed from log for table.

**Comment by twwilliams** [comment]
OK. I'll close this item. Thanks for doing what you could to track this down.
